/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData ok_circled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_empty = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_empty = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circled = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_circled = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_1 = IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 = IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xf06e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash = IconData(0xf070, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_alt = IconData(0xf0e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_alt = IconData(0xf0f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xf129, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_down = IconData(0xf13a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock_alt = IconData(0xf13e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_off = IconData(0xf1f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_off_empty = IconData(0xf1f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xf1f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_plus = IconData(0xf217, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer_full = IconData(0xf2c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData utensil_spoon = IconData(0xf2e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capsules = IconData(0xf46b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pills = IconData(0xf484, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shipping_fast = IconData(0xf48b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syringe = IconData(0xf48e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablets = IconData(0xf490, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer = IconData(0xf491, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
